nfq_library:
    resource: "@NfqLibraryBundle/Resources/config/routing.yml"
    prefix:   /

nfq_weather:
    resource: "@NfqWeatherBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
