services:
    nfq.weather:
        class: Nfq\WeatherBundle\WeatherGetter
        arguments: ["@open_weather_map"]
        
    open_weather_map:
#        class: Nfq\WeatherBundle\WeatherProvider\OpenWeatherMap
        class: Nfq\WeatherBundle\WeatherProvider\ForecastIO

#    nfq_weather.example:
#        class: Nfq\WeatherBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
