default_index:
    path:     /
    defaults: { _controller: NfqLibraryBundle:Default:index }

default_index_hello_name:
    path:     /hello/{name}
    defaults: { _controller: NfqLibraryBundle:Default:hello }
    
bookdata_isbn:
    path:     /bookdata/{isbn}
    defaults: { _controller: NfqLibraryBundle:BookData:index }

booklist_books:
    path:     /books
    defaults: { _controller: NfqLibraryBundle:BookList:books }
    
booklist_books_type:
    path:     /books/{type}
    defaults: { _controller: NfqLibraryBundle:BookList:books }

booklist_search:
    path:     /search
    defaults: { _controller: NfqLibraryBundle:BookList:search }

booklist_search_str:
    path:     /search/{str}
    defaults: { _controller: NfqLibraryBundle:BookList:search }
