Nfq\LibraryBundle\Entity\Books:
    type: entity
    table: books
    indexes:
        fk_books_owner_id:
            columns:
                - owner_id
        fk_books_description_id:
            columns:
                - description_id
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        addedAt:
            type: date
            nullable: false
            comment: ''
            column: added_at
    manyToOne:
        owner:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                owner_id:
                    referencedColumnName: id
            orphanRemoval: false
        description:
            targetEntity: Descriptions
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                description_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
