Nfq\LibraryBundle\Entity\Orders:
    type: entity
    table: orders
    indexes:
        fk_Orders_Users1_idx:
            columns:
                - reader_id
        fk_Orders_Books1_idx:
            columns:
                - book_id
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        reservedAt:
            type: date
            nullable: true
            comment: ''
            column: reserved_at
        takenAt:
            type: date
            nullable: true
            comment: ''
            column: taken_at
        toReturnAt:
            type: date
            nullable: true
            comment: ''
            column: to_return_at
        returnedAt:
            type: date
            nullable: true
            comment: ''
            column: returned_at
    manyToOne:
        book:
            targetEntity: Books
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                book_id:
                    referencedColumnName: id
            orphanRemoval: false
        reader:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                reader_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
