Nfq\LibraryBundle\Entity\Orders:
    type: entity
    table: orders
    indexes:
        fk_orders_reader_id:
            columns:
                - reader_id
        fk_orders_description_id:
            columns:
                - description_id
        fk_orders_book_id:
            columns:
                - book_id
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        readerId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            column: reader_id
        descriptionId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            column: description_id
        reservedAt:
            type: date
            nullable: false
            comment: ''
            column: reserved_at
        bookId:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
            column: book_id
        takenAt:
            type: date
            nullable: true
            comment: ''
            column: taken_at
        toReturnAt:
            type: date
            nullable: true
            comment: ''
            column: to_return_at
        returnedAt:
            type: date
            nullable: true
            comment: ''
            column: returned_at
    manyToOne:
        reader:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                reader_id:
                    referencedColumnName: id
            orphanRemoval: true
        description:
            targetEntity: Descriptions
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                description_id:
                    referencedColumnName: id
            orphanRemoval: true
        book:
            targetEntity: Books
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                book_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
