Nfq\LibraryBundle\Entity\Users:
    type: entity
    table: users
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstname:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        lastname:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 254
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        salt:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        isAdmin:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: is_admin
    manyToMany:
        tag:
            targetEntity: Tags
            cascade: {  }
            mappedBy: null
            inversedBy: user
            joinTable:
                name: user_tags
                joinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: tag_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
